#!/bin/sh
# gen-auth-vectors.sh — extract the authentication test vectors from the RFCs that define them, into
# tests/unit/src/auth_vectors.kama. The generated file is committed; this script is how it was made, and how
# it is checked: run it, and `git diff` must be empty.
#
#   RFC 1321 Appendix A.5   the MD5 test suite (seven inputs, including two the RFC wraps across lines)
#   RFC 7677 Section 3      the SCRAM-SHA-256 example exchange (user "user", password "pencil")
#   OpenSSL                 PostgreSQL's md5 password response for one user, password and salt, computed by an
#                           independent MD5 (`openssl dgst -md5`); the integration tests check it against servers
#
# Each RFC text is pinned by SHA256, so a vector can never change underneath the tests. RFC_DIR may name a
# directory holding rfc1321.txt and rfc7677.txt already (the hashes are checked either way).
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
OUT="$ROOT/tests/unit/src/auth_vectors.kama"
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

fetch() {  # fetch <name> <sha256>
    if [ -n "${RFC_DIR:-}" ] && [ -f "$RFC_DIR/$1" ]; then cp "$RFC_DIR/$1" "$tmp/$1"
    else curl -fsSL -o "$tmp/$1" "https://www.rfc-editor.org/rfc/$1"; fi
    got=$(shasum -a 256 "$tmp/$1" | cut -d' ' -f1)
    [ "$got" = "$2" ] || { echo "gen-auth-vectors: $1 sha256 $got, want $2" >&2; exit 1; }
}
fetch rfc1321.txt 284a79d148400d9cd2a423211d1103b5cef0fb9256a4cbe6d7ebe5197c3149dd
fetch rfc7677.txt 81490224a838bf5da7bfcce53e4ec1b1d2f69717c43c600111dec6652a386c71

# MD5 ("input") = digest — an entry may wrap after `=` or inside the quoted input; join until the digest.
awk '
    /^MD5 \("/ { entry = $0; collecting = 1 }
    collecting && !/^MD5 \("/ { entry = entry $0 }
    collecting && entry ~ /= *[0-9a-f]{32} *$/ {
        match(entry, /\("[^"]*"\)/); input = substr(entry, RSTART + 2, RLENGTH - 4)
        match(entry, /= *[0-9a-f]{32} *$/); digest = substr(entry, RSTART, RLENGTH)
        gsub(/[= ]/, "", digest)
        printf "%s\t%s\n", input, digest
        collecting = 0
    }
' "$tmp/rfc1321.txt" > "$tmp/md5.tsv"
[ "$(wc -l < "$tmp/md5.tsv" | tr -d ' ')" = 7 ] || { echo "gen-auth-vectors: expected 7 MD5 vectors" >&2; exit 1; }

# The SCRAM exchange: four messages, each "C: " or "S: " and possibly continued on indented lines.
awk '
    /^   [CS]: / { if (msg != "") print msg; msg = substr($0, 7); next }
    msg != "" && /^      [^ ]/ { sub(/^ +/, ""); msg = msg $0; next }
    msg != "" && /^ *$/ { print msg; msg = "" }
    END { if (msg != "") print msg }
' "$tmp/rfc7677.txt" > "$tmp/scram.txt"
[ "$(wc -l < "$tmp/scram.txt" | tr -d ' ')" = 4 ] || { echo "gen-auth-vectors: expected 4 SCRAM messages" >&2; exit 1; }
client_first=$(sed -n 1p "$tmp/scram.txt")
server_first=$(sed -n 2p "$tmp/scram.txt")
client_final=$(sed -n 3p "$tmp/scram.txt")
server_final=$(sed -n 4p "$tmp/scram.txt")
client_nonce=$(printf '%s' "$client_first" | sed 's/.*,r=//')

# md5 response = "md5" + md5(hex(md5(password + user)) + salt), salt 01 02 03 04.
OPENSSL=${OPENSSL:-openssl}
md5_user=kp_md5
md5_password=kp_md5_pw
md5_inner=$(printf '%s%s' "$md5_password" "$md5_user" | "$OPENSSL" dgst -md5 -r | cut -d' ' -f1)
md5_outer=$(printf '%s\001\002\003\004' "$md5_inner" | "$OPENSSL" dgst -md5 -r | cut -d' ' -f1)

{
    echo '// GENERATED by tools/gen-auth-vectors.sh from RFC 1321 (Appendix A.5) and RFC 7677 (Section 3). Do not edit:'
    echo '// change the script and run it again.'
    echo 'import { std::collections::DynamicArray };'
    echo 'export { md5Inputs, md5Digests, scramUser, scramPassword, scramClientNonce, scramClientFirst, scramServerFirst,'
    echo '         scramClientFinal, scramServerFinal, md5User, md5PasswordText, md5Inner, md5Response };'
    echo
    echo 'fn DynamicArray<string> md5Inputs() {'
    echo '    DynamicArray<string> v = DynamicArray.empty();'
    cut -f1 "$tmp/md5.tsv" | while IFS= read -r line; do printf '    v.add(item: "%s");\n' "$line"; done
    echo '    return v;'
    echo '}'
    echo
    echo 'fn DynamicArray<string> md5Digests() {'
    echo '    DynamicArray<string> v = DynamicArray.empty();'
    cut -f2 "$tmp/md5.tsv" | while IFS= read -r line; do printf '    v.add(item: "%s");\n' "$line"; done
    echo '    return v;'
    echo '}'
    echo
    echo 'fn string scramUser() { return "user"; }'
    echo 'fn string scramPassword() { return "pencil"; }'
    printf 'fn string scramClientNonce() { return "%s"; }\n' "$client_nonce"
    printf 'fn string scramClientFirst() { return "%s"; }\n' "$client_first"
    printf 'fn string scramServerFirst() { return "%s"; }\n' "$server_first"
    printf 'fn string scramClientFinal() { return "%s"; }\n' "$client_final"
    printf 'fn string scramServerFinal() { return "%s"; }\n' "$server_final"
    echo
    echo '// md5(password ‖ user) in hex (what pg_authid stores, after "md5"), and the response to salt 01 02 03 04.'
    printf 'fn string md5User() { return "%s"; }\n' "$md5_user"
    printf 'fn string md5PasswordText() { return "%s"; }\n' "$md5_password"
    printf 'fn string md5Inner() { return "%s"; }\n' "$md5_inner"
    printf 'fn string md5Response() { return "md5%s"; }\n' "$md5_outer"
} > "$OUT"

echo "gen-auth-vectors: wrote $(basename "$OUT") (7 MD5 vectors, the RFC 7677 exchange)"
