#!/bin/sh
# gen-pg-catalog.sh — PostgreSQL's own tables of error codes and built-in types, extracted rather than retyped:
#
#   src/sqlstate/sqlstate.kama   every SQLSTATE in src/backend/utils/errcodes.txt, as an int32 constant packed
#                                the way PostgreSQL packs it (MAKE_SQLSTATE: six bits a character), named after
#                                its ERRCODE_ macro without the prefix (UNIQUE_VIOLATION, SERIALIZATION_FAILURE…),
#                                with the condition name PL/pgSQL uses
#   src/types/oids.kama          every built-in type in src/include/catalog/pg_type.dat: its OID as a uint32
#                                constant (INT4 = 23), its array type's (INT4_ARRAY = 1007), and its name
#
# The generated files are committed; run this script and `git diff` must be empty. The PostgreSQL source is
# pinned to the same REL_18_STABLE commit as tools/gen-libpq-tables.sh, and each file by SHA256. PG_SRC_DIR may
# name a directory holding errcodes.txt and pg_type.dat already (hashes still checked).
set -eu

COMMIT=c45ba888d7af7b38e33832a0e240e34ca98ef866
ERRCODES_SHA=6e8de346643ba84aa3c9c6a73360acfc7b2dfb89162c06c08ce9bf5bcd5bbcba
PG_TYPE_SHA=5f5887b75677cba2d4a1a0cfeb355df5ed91f85d385fac88bd8d7c605b3578f9

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

fetch() {  # fetch <path in the postgres tree> <local name> <sha256>
    if [ -n "${PG_SRC_DIR:-}" ] && [ -f "$PG_SRC_DIR/$2" ]; then cp "$PG_SRC_DIR/$2" "$tmp/$2"
    else curl -fsSL -o "$tmp/$2" "https://raw.githubusercontent.com/postgres/postgres/$COMMIT/$1"; fi
    got=$(shasum -a 256 "$tmp/$2" | cut -d' ' -f1)
    [ "$got" = "$3" ] || { echo "gen-pg-catalog: $2 sha256 $got, want $3" >&2; exit 1; }
}
fetch src/backend/utils/errcodes.txt errcodes.txt "$ERRCODES_SHA"
fetch src/include/catalog/pg_type.dat pg_type.dat "$PG_TYPE_SHA"

mkdir -p "$ROOT/src/sqlstate" "$ROOT/src/types"

perl -e '
    open my $f, "<", $ARGV[0] or die;
    my @rows;
    while (<$f>) {
        next unless /^([0-9A-Z]{5})\s+([EWS])\s+ERRCODE_([A-Z0-9_]+)(?:\s+([a-z0-9_]+))?\s*$/;
        my ($code, $kind, $macro, $cond) = ($1, $2, $3, $4 // "");
        my $packed = 0;
        for my $i (0 .. 4) { $packed += ((ord(substr($code, $i, 1)) - 48) & 63) << (6 * $i); }
        push @rows, [$code, $macro, $cond, $packed];
    }
    @rows >= 250 or die "only " . scalar(@rows) . " SQLSTATEs";
    print "// GENERATED by tools/gen-pg-catalog.sh from PostgreSQL REL_18_STABLE ($ARGV[1]),\n";
    print "// src/backend/utils/errcodes.txt. Do not edit: change the script and run it again.\n";
    print "import { std::collections::DynamicArray, std::collections::ConstView };\n";
    print "export { sqlstateText, sqlstateCode, sqlstateClass, conditionName,\n         ";
    print join(", ", map { $_->[1] } @rows);
    print " };\n\n";
    print "// postgres::sqlstate — every SQLSTATE PostgreSQL defines. A code is an int32 packed as the server packs it\n";
    print "// (MAKE_SQLSTATE: each of the five characters as six bits, the first lowest), so comparing two is one\n";
    print "// integer compare: `if (err.sqlstate() == UNIQUE_VIOLATION) { … }`.\n\n";
    for my $r (@rows) { printf "comptime int32 %s = %d;   // %s\n", $r->[1], $r->[3], $r->[0]; }
    print "\n// The five-character text of a packed code, e.g. \"23505\".\n";
    print "fn string sqlstateText(int32 code) {\n";
    print "    InlineArray<uint8>#(5) chars = [0ui8; 5];\n    isize i = 0;\n";
    print "    while (i < 5) { chars[cast<usize>(i)] = truncate<uint8>(((code >> cast<int32>(6 * i)) & 63) + 48); i = i + 1; }\n";
    print "    return textOf(b: chars.view());\n}\n\n";
    print "unsafe fn string textOf(ConstView<uint8> b) { return kama_string_from_raw(src: b.dataPtr(), start: 0, len: b.length()); }\n";
    print "extern fn string kama_string_from_raw(UnsafeConstPtr<uint8> src, isize start, isize len);\n\n";
    print "// The packed code for five characters of [0-9A-Z], or -1 if `text` is not one.\n";
    print "fn int32 sqlstateCode(const ref string text) { return codeOf(b: text.bytes()); }\n\n";
    print "fn int32 codeOf(ConstView<uint8> b) {\n    if (b.length() != 5) { return -1; }\n    int32 code = 0;\n    isize i = 0;\n";
    print "    while (i < 5) {\n        uint8 c = b[i];\n        if (!((c >= 48ui8 && c <= 57ui8) || (c >= 65ui8 && c <= 90ui8))) { return -1; }\n";
    print "        code = code + ((cast<int32>(c) - 48) << cast<int32>(6 * i));\n        i = i + 1;\n    }\n    return code;\n}\n\n";
    print "// The class of a code: its first two characters, as a code with the last three \"000\" (23505 -> 23000,\n";
    print "// INTEGRITY_CONSTRAINT_VIOLATION). Every code in a class shares this.\n";
    print "fn int32 sqlstateClass(int32 code) { return code & 4095; }\n\n";
    print "// The condition name PL/pgSQL uses for a code (\"unique_violation\"), if it has one.\n";
    print "fn Optional<string> conditionName(int32 code) {\n";
    for my $r (@rows) { next if $r->[2] eq ""; printf "    if (code == %d) { return Optional::Some(value: \"%s\"); }\n", $r->[3], $r->[2]; }
    print "    return Optional::None;\n}\n";
' "$tmp/errcodes.txt" "$COMMIT" > "$ROOT/src/sqlstate/sqlstate.kama"

perl -0777 -e '
    my $src = do { local $/; open my $f, "<", $ARGV[0] or die; <$f> };
    my @rows;
    # An entry ends at a quoted value followed by "}" at the end of its line; a "}" inside a description
    # (line\x27s "{A,B,C}") is never there.
    while ($src =~ /\{\s*oid\s*=>\s*\x27(\d+)\x27(.*?)\x27\s*\},?[ \t]*\n/sg) {
        my ($oid, $body) = ($1, $2);
        my ($name) = $body =~ /typname\s*=>\s*\x27([^\x27]+)\x27/ or die "no typname for $oid";
        my ($array) = $body =~ /array_type_oid\s*=>\s*\x27(\d+)\x27/;
        push @rows, [$oid, $name, $array];
    }
    @rows >= 100 or die "only " . scalar(@rows) . " types";
    my @consts;
    for my $r (@rows) {
        my $c = uc $r->[1];
        push @consts, [$c, $r->[0], $r->[1]];
        push @consts, ["${c}_ARRAY", $r->[2], "_" . $r->[1]] if defined $r->[2];
    }
    print "// GENERATED by tools/gen-pg-catalog.sh from PostgreSQL REL_18_STABLE ($ARGV[1]),\n";
    print "// src/include/catalog/pg_type.dat. Do not edit: change the script and run it again.\n";
    print "export { typeName, elementType,\n         " . join(", ", map { $_->[0] } @consts) . " };\n\n";
    print "// The OID of every built-in type, and of its array type (the element name, then _ARRAY). These OIDs are fixed\n";
    print "// across PostgreSQL versions; a type an extension adds (hstore, citext, vector) has an OID chosen at CREATE\n";
    print "// EXTENSION time and must be looked up by name.\n\n";
    for my $c (@consts) { printf "comptime uint32 %s = %dui32;\n", $c->[0], $c->[1]; }
    print "\n// The name of a built-in type (\"int4\", \"_int4\" for its array), or \"\" for an OID that is not one.\n";
    print "fn string typeName(uint32 oid) {\n";
    for my $c (@consts) { printf "    if (oid == %dui32) { return \"%s\"; }\n", $c->[1], $c->[2]; }
    print "    return \"\";\n}\n";
    print "\n// The element type of a built-in array type (INT4 for INT4_ARRAY), or 0 for an OID that is not one.\n";
    print "fn uint32 elementType(uint32 arrayOid) {\n";
    for my $r (@rows) { next unless defined $r->[2]; printf "    if (arrayOid == %dui32) { return %dui32; }\n", $r->[2], $r->[0]; }
    print "    return 0ui32;\n}\n";
' "$tmp/pg_type.dat" "$COMMIT" > "$ROOT/src/types/oids.kama"

echo "gen-pg-catalog: $(grep -c '^comptime int32' "$ROOT/src/sqlstate/sqlstate.kama") SQLSTATEs, $(grep -c '^comptime uint32' "$ROOT/src/types/oids.kama") type OIDs (PostgreSQL ${COMMIT%${COMMIT#????????}})"
