#!/bin/sh
# gen-saslprep.sh — SASLprep (RFC 4013) as PostgreSQL does it, extracted rather than retyped:
#
#   src/stringprep/tables.kama           the six stringprep tables of src/common/saslprep.c, each a sorted list of
#                                        inclusive code point ranges, with the search the password code calls
#   tests/unit/src/saslprep_vectors.kama what PostgreSQL says SASLprep does:
#                                        - the outcome per input of src/test/modules/test_saslprep's expected
#                                          output (every ASCII byte);
#                                        - the SCRAM verifier a live server stores for each password below.
#                                          The server runs pg_saslprep before it hashes, so a client that
#                                          prepares a password the same way derives the same StoredKey and
#                                          ServerKey from the verifier's salt.
#
# Both generated files are committed. This script is how they were made, and how they are checked: run it, and
# `git diff` must be empty (the server's random salts aside: the verifiers change, and both stay correct).
# The PostgreSQL source is pinned to one commit of master, the first with test_saslprep, and each file by SHA256.
# PG_SRC_DIR may name a directory holding saslprep.c and test_saslprep.out already (hashes still checked).
#
#   tools/pg.sh up --version 18 && tools/gen-saslprep.sh [--version 18]
set -eu

COMMIT=45277ca0d1cb6dbe722a01b3b5461c30abd40eee
SASLPREP_SHA=5dadb3ae0705c5e02558eb0272582b9b88cfd52e74904b8263516ffdcced8cb6
TEST_OUT_SHA=a803467e4f1c79faedf69d7b1e34d8427e19794159797223d8b7df273cc7576c

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
VERSION=18
if [ "${1:-}" = "--version" ]; then VERSION=${2:?--version needs a value}; fi
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

fetch() {  # fetch <path in the postgres tree> <local name> <sha256>
    if [ -n "${PG_SRC_DIR:-}" ] && [ -f "$PG_SRC_DIR/$2" ]; then cp "$PG_SRC_DIR/$2" "$tmp/$2"
    else curl -fsSL -o "$tmp/$2" "https://raw.githubusercontent.com/postgres/postgres/$COMMIT/$1"; fi
    got=$(shasum -a 256 "$tmp/$2" | cut -d' ' -f1)
    [ "$got" = "$3" ] || { echo "gen-saslprep: $2 sha256 $got, want $3" >&2; exit 1; }
}
fetch src/common/saslprep.c saslprep.c "$SASLPREP_SHA"
fetch src/test/modules/test_saslprep/expected/test_saslprep.out test_saslprep.out "$TEST_OUT_SHA"

# ---- the tables ---------------------------------------------------------------------------------------------
mkdir -p "$ROOT/src/stringprep"
perl -0777 -e '
    my $src = do { local $/; open my $f, "<", $ARGV[0] or die; <$f> };
    my %name = (non_ascii_space_ranges => ["NON_ASCII_SPACE", "isNonAsciiSpace", "C.1.2: mapped to SPACE"],
                commonly_mapped_to_nothing_ranges => ["MAPPED_TO_NOTHING", "isMappedToNothing", "B.1: mapped to nothing"],
                prohibited_output_ranges => ["PROHIBITED_OUTPUT", "isProhibitedOutput", "C.1.2, C.2.1-C.9: prohibited output"],
                unassigned_codepoint_ranges => ["UNASSIGNED", "isUnassigned", "A.1: unassigned in Unicode 3.2"],
                RandALCat_codepoint_ranges => ["RANDAL_CAT", "isRandALCat", "D.1: right-to-left (RandALCat)"],
                LCat_codepoint_ranges => ["L_CAT", "isLCat", "D.2: left-to-right (LCat)"]);
    my @order = qw(non_ascii_space_ranges commonly_mapped_to_nothing_ranges prohibited_output_ranges
                   unassigned_codepoint_ranges RandALCat_codepoint_ranges LCat_codepoint_ranges);
    my %tables;
    while ($src =~ /static const char32_t (\w+)\[\] =\s*\{(.*?)\};/sg) {
        my ($n, $body) = ($1, $2);
        $body =~ s{/\*.*?\*/}{}sg;
        my @hex = ($body =~ /0x([0-9A-Fa-f]+)/g);
        die "odd table $n" if @hex % 2;
        $tables{$n} = \@hex;
    }
    for my $n (@order) { die "no table $n" unless $tables{$n}; }
    print "// GENERATED by tools/gen-saslprep.sh from PostgreSQL master ($ARGV[1]), src/common/saslprep.c.\n";
    print "// Do not edit: change the script and run it again.\n//\n";
    print "// The stringprep tables (RFC 3454) that SASLprep uses, as PostgreSQL holds them: each a sorted list of\n";
    print "// inclusive code point ranges, first and last, each with the search the password code calls.\n";
    print "import { std::collections::ConstView };\n";
    print "export { " . join(", ", map { $name{$_}[1] } @order) . " };\n\n";
    for my $n (@order) {
        my ($const, $fn, $what) = @{$name{$n}};
        my @hex = @{$tables{$n}};
        print "// $what\n";
        print "comptime InlineArray<uint32>#(" . scalar(@hex) . ") $const = [\n";
        for (my $i = 0; $i < @hex; $i += 8) {
            my $end = $i + 7; $end = $#hex if $end > $#hex;
            print "    " . join(", ", map { "0x" . uc($_) . "ui32" } @hex[$i..$end]) . ($end < $#hex ? ",\n" : "\n");
        }
        print "];\n";
        print "fn bool $fn(uint32 code) { return inRanges(code: code, ranges: $const.view()); }\n\n";
    }
    print <<"KAMA";
// is_code_in_table: a binary search over the ranges.
fn bool inRanges(uint32 code, ConstView<uint32> ranges) {
    if (code < ranges[0] || code > ranges[ranges.length() - 1]) { return false; }
    isize lo = 0;
    isize hi = ranges.length() / 2 - 1;
    while (lo <= hi) {
        isize mid = (lo + hi) / 2;
        if (code < ranges[mid * 2]) { hi = mid - 1; }
        else if (code > ranges[mid * 2 + 1]) { lo = mid + 1; }
        else { return true; }
    }
    return false;
}
KAMA
' "$tmp/saslprep.c" "$COMMIT" > "$ROOT/src/stringprep/tables.kama"

# ---- the server's verifiers ---------------------------------------------------------------------------------
# Each password as its code points. The cases are RFC 4013's examples, and one or more for each step of the
# algorithm: mapping, NFKC, prohibited output, an unassigned code point, and the bidi rule both ways.
cat > "$tmp/passwords" <<'EOF'
0049 00AD 0058
0075 0073 0065 0072
0055 0053 0045 0052
00AA
2168
0007
0627 0031
FF30 FF21 FF33 FF33
FB01
0065 0301
0070 00A0 0077
0070 200B 0077
0070 200D 0077
0627 0628
0627 0061 0628
1100 1161
E000
1F600
00BD
00AD
FE8D
0041 0300 0301
212B
00C5
1E9B 0323
03D3
0020 0020
3000
00DF
0130
2126
0041 FE0F
EOF

perl -ne '
    chomp; next unless length;
    my @cp = split / /;
    my $lit = join("", map { my $v = hex($_); $v > 0xFFFF ? sprintf("\\+%06X", $v) : sprintf("\\%04X", $v) } @cp);
    print "ALTER ROLE kp_gen_saslprep PASSWORD U&\x27$lit\x27;\n";
    print "SELECT rolpassword FROM pg_authid WHERE rolname = \x27kp_gen_saslprep\x27;\n";
' "$tmp/passwords" > "$tmp/body.sql"
{
    echo "SET password_encryption = 'scram-sha-256';"
    echo "SET client_min_messages = warning;"
    echo "DROP ROLE IF EXISTS kp_gen_saslprep;"
    echo "CREATE ROLE kp_gen_saslprep;"
    cat "$tmp/body.sql"
    echo "DROP ROLE kp_gen_saslprep;"
} > "$tmp/query.sql"
"$ROOT/tools/pg.sh" psql --version "$VERSION" -q -A -t -f - < "$tmp/query.sql" > "$tmp/verifiers"
expected=$(grep -c . "$tmp/passwords")
got=$(grep -c '^SCRAM-SHA-256\$' "$tmp/verifiers")
[ "$got" = "$expected" ] || { echo "gen-saslprep: $got verifiers for $expected passwords" >&2; cat "$tmp/verifiers" >&2; exit 1; }
server=$("$ROOT/tools/pg.sh" psql --version "$VERSION" -A -t -c 'SHOW server_version')

perl -e '
    my ($passwords, $verifiers, $testout, $commit, $server) = @ARGV;
    sub utf8hex { my $v = shift; my $s = chr($v); utf8::encode($s); return unpack("H*", $s); }
    open my $p, "<", $passwords or die; my @pw = grep { length } map { chomp; $_ } <$p>;
    open my $v, "<", $verifiers or die; my @ver = grep { /^SCRAM-SHA-256\$/ } map { chomp; $_ } <$v>;
    # test_saslprep.out: the single-byte table. Its one other case, an incomplete UTF-8 sequence, cannot be a
    # kama string, which is always UTF-8, so it has no vector here.
    open my $t, "<", $testout or die;
    my (@sin, @sout);
    while (<$t>) {
        next unless /\|\s*\\x([0-9a-f]+)\s*\|\s*\((.*)\)\s*$/;
        my ($in, $res) = ($1, $2);
        $res =~ /^(?:"\\\\x([0-9a-f]*)")?,(\w+)$/ or die "unrecognized result $res";
        push @sin, $in;
        push @sout, $2 eq "SUCCESS" ? "SUCCESS $1" : $2;
    }
    die "no status vectors" unless @sin == 128;
    print "// GENERATED by tools/gen-saslprep.sh. Do not edit: run the script again.\n//\n";
    print "// SASLprep as PostgreSQL does it:\n";
    print "// - saslprepStatus*: src/test/modules/test_saslprep/expected/test_saslprep.out at PostgreSQL master\n";
    print "//   ($commit):\n";
    print "//   an input, in hex, and its outcome (\"SUCCESS <hex of the output>\" or \"PROHIBITED\").\n";
    print "// - saslprepServer*: a password, as UTF-8 in hex, and the SCRAM verifier the server stored for it\n";
    print "//   (\"SCRAM-SHA-256\$<iterations>:<salt>\$<StoredKey>:<ServerKey>\"), from PostgreSQL $server.\n";
    print "import { std::collections::DynamicArray };\n";
    print "export { saslprepStatusInputs, saslprepStatusResults, saslprepServerPasswords, saslprepServerVerifiers };\n\n";
    my @fns = (["saslprepStatusInputs", \@sin], ["saslprepStatusResults", \@sout],
               ["saslprepServerPasswords", [map { join("", map { utf8hex(hex($_)) } split / /) } @pw]],
               ["saslprepServerVerifiers", \@ver]);
    for my $f (@fns) {
        my ($name, $vals) = @$f;
        print "fn DynamicArray<string> $name() {\n    DynamicArray<string> v = DynamicArray.empty();\n";
        for my $x (@$vals) { die "\${ or quote in a vector" if $x =~ /\$\{|"/; print "    v.add(item: \"$x\");\n"; }
        print "    return v;\n}\n\n";
    }
' "$tmp/passwords" "$tmp/verifiers" "$tmp/test_saslprep.out" "$COMMIT" "$server" > "$ROOT/tests/unit/src/saslprep_vectors.kama"

echo "gen-saslprep: tables from $COMMIT; $got verifiers from PostgreSQL $server"
