#!/bin/sh
# gen-libpq-tables.sh — what this package takes from libpq's source, extracted rather than retyped:
#
#   src/conninfo/keywords.kama          libpq's connection keywords in its own order (PQconninfoOptions in
#                                       fe-connect.c), each with its environment variable and compiled default;
#                                       and the run-time settings libpq takes from the environment into every
#                                       StartupMessage (EnvironmentOptions, e.g. PGTZ -> timezone)
#   tests/unit/src/uri_vectors.kama     libpq's URI regression cases (src/interfaces/libpq/t/001_uri.pl): the
#                                       input, what libpq_uri_regress prints, and the error it reports
#
# Both generated files are committed. This script is how they were made, and how they are checked: run it, and
# `git diff` must be empty. The PostgreSQL source is pinned to one commit of REL_18_STABLE, and each file by
# SHA256. PG_SRC_DIR may name a directory holding fe-connect.c and 001_uri.pl already (hashes still checked).
#
# Defaults that are macros in fe-connect.c take the value libpq has when built WITH SSL and WITHOUT GSSAPI,
# which is what this package is: sslmode "prefer", sslcertmode "allow", channel_binding "prefer", gssencmode
# "disable".
set -eu

COMMIT=c45ba888d7af7b38e33832a0e240e34ca98ef866
FE_CONNECT_SHA=44a6e386cbfd67ebe768d6ef5493098119c2e6b4796239d53e5ed7b122b206a5
URI_TEST_SHA=91e1b99121e0117dd8d58336c9818ac941cbffb01455f74c3e0ef1217fe145e6

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

fetch() {  # fetch <path in the postgres tree> <local name> <sha256>
    if [ -n "${PG_SRC_DIR:-}" ] && [ -f "$PG_SRC_DIR/$2" ]; then cp "$PG_SRC_DIR/$2" "$tmp/$2"
    else curl -fsSL -o "$tmp/$2" "https://raw.githubusercontent.com/postgres/postgres/$COMMIT/$1"; fi
    got=$(shasum -a 256 "$tmp/$2" | cut -d' ' -f1)
    [ "$got" = "$3" ] || { echo "gen-libpq-tables: $2 sha256 $got, want $3" >&2; exit 1; }
}
fetch src/interfaces/libpq/fe-connect.c fe-connect.c "$FE_CONNECT_SHA"
fetch src/interfaces/libpq/t/001_uri.pl 001_uri.pl "$URI_TEST_SHA"

# A kama string literal: backslash and double quote escaped; "${" cannot appear in these inputs (checked).
mkdir -p "$ROOT/src/conninfo"
perl -0777 -e '
    my $src = do { local $/; open my $f, "<", $ARGV[0] or die; <$f> };
    $src =~ /PQconninfoOptions\[\] = \{(.*?)\n\};/s or die "no PQconninfoOptions";
    my $table = $1;
    my %macro = (DEF_PGPORT_STR => "5432", DefaultOption => "", DefaultChannelBinding => "prefer",
                 DefaultSSLMode => "prefer", DefaultSSLNegotiation => "postgres", DefaultGSSMode => "disable",
                 PG_KRB_SRVNAM => "postgres", DefaultTargetSessionAttrs => "any",
                 DefaultLoadBalanceHosts => "disable");
    my @rows;
    while ($table =~ /\{\s*"([a-z_]+)"\s*,\s*(NULL|"[A-Z_]+")\s*,\s*(NULL|"[^"]*"|[A-Za-z_]+)/sg) {
        my ($kw, $env, $def) = ($1, $2, $3);
        $env = $env eq "NULL" ? "" : substr($env, 1, -1);
        my $has = $def eq "NULL" ? "false" : "true";
        if ($def eq "NULL") { $def = ""; }
        elsif ($def =~ /^"(.*)"$/) { $def = $1; }
        else { exists $macro{$def} or die "unknown default macro $def for $kw"; $def = $macro{$def}; }
        push @rows, [$kw, $env, $has, $def];
    }
    @rows >= 40 or die "only " . scalar(@rows) . " keywords";
    print "// GENERATED by tools/gen-libpq-tables.sh from PostgreSQL REL_18_STABLE ($ARGV[1]),\n";
    print "// src/interfaces/libpq/fe-connect.c, PQconninfoOptions. Do not edit: change the script and run it again.\n";
    print "import { std::collections::DynamicArray };\nexport { Keyword, libpqKeywords, EnvironmentOption, libpqEnvironmentOptions };\n\n";
    print "// One libpq connection keyword: its name, the environment variable that supplies it (\"\" if none), and\n";
    print "// libpq\x27s compiled default when it has one (with SSL, without GSSAPI).\n";
    print "type resource Keyword {\n    string keyword;\n    string envVar;\n    bool defaulted = false;\n    string defaultText;\n";
    print "    public ctor of(string keyword, string envVar, bool defaulted, string defaultText) {\n";
    print "        this.keyword = give keyword; this.envVar = give envVar; this.defaulted = defaulted; this.defaultText = give defaultText;\n    }\n";
    print "    public const fn const ref string name() { return this.keyword; }\n";
    print "    public const fn const ref string environment() { return this.envVar; }\n";
    print "    public const fn bool hasDefault() { return this.defaulted; }\n";
    print "    public const fn const ref string defaultValue() { return this.defaultText; }\n}\n\n";
    print "// Every keyword libpq accepts, in its own order (the order libpq_uri_regress prints them in).\n";
    print "fn DynamicArray<Keyword> libpqKeywords() {\n    DynamicArray<Keyword> k = DynamicArray.withCapacity(capacity: " . scalar(@rows) . ");\n";
    for my $r (@rows) { printf "    k.add(item: Keyword.of(keyword: \"%s\", envVar: \"%s\", defaulted: %s, defaultText: \"%s\"));\n", @$r; }
    print "    return k;\n}\n";
    $src =~ /EnvironmentOptions\[\] =\s*\{(.*?)\n\};/s or die "no EnvironmentOptions";
    my $envtab = $1;
    my @envs;
    while ($envtab =~ /\{\s*"([A-Z_]+)"\s*,\s*"([a-z_]+)"\s*\}/sg) { push @envs, [$1, $2]; }
    @envs >= 2 or die "only " . scalar(@envs) . " environment options";
    print "\n// A run-time setting libpq sends in every StartupMessage when its environment variable is set (and is not\n";
    print "// \"default\"): EnvironmentOptions in fe-connect.c.\n";
    print "type resource EnvironmentOption {\n    string envVar;\n    string setting;\n";
    print "    public ctor of(string envVar, string setting) { this.envVar = give envVar; this.setting = give setting; }\n";
    print "    public const fn const ref string environment() { return this.envVar; }\n";
    print "    public const fn const ref string parameter() { return this.setting; }\n}\n\n";
    print "// In libpq\x27s order, which is the order they are sent in.\n";
    print "fn DynamicArray<EnvironmentOption> libpqEnvironmentOptions() {\n    DynamicArray<EnvironmentOption> e = DynamicArray.withCapacity(capacity: " . scalar(@envs) . ");\n";
    for my $r (@envs) { printf "    e.add(item: EnvironmentOption.of(envVar: \"%s\", setting: \"%s\"));\n", @$r; }
    print "    return e;\n}\n";
' "$tmp/fe-connect.c" "$COMMIT" > "$ROOT/src/conninfo/keywords.kama"

perl -e '
    my $src = do { local $/; open my $f, "<", $ARGV[0] or die; <$f> };
    $src =~ /(my \@tests = \(.*?\n\s*\]\);)/s or die "no \@tests block";
    my @tests; (my $code = $1) =~ s/^my //; eval $code; die $@ if $@;
    @tests >= 60 or die "only " . scalar(@tests) . " URI tests";
    sub lit { my $s = shift; die "\${ in a vector" if $s =~ /\$\{/; $s =~ s/\\/\\\\/g; $s =~ s/"/\\"/g; return "\"$s\""; }
    print "// GENERATED by tools/gen-libpq-tables.sh from PostgreSQL REL_18_STABLE ($ARGV[1]),\n";
    print "// src/interfaces/libpq/t/001_uri.pl. Do not edit: change the script and run it again.\n";
    print "//\n// Each case: the connection string, what libpq_uri_regress prints for it (every option set and not at its\n";
    print "// default, in libpq\x27s keyword order, then \"(local)\" or \"(inet)\"), the error libpq reports instead (without\n";
    print "// the program-name prefix), and the environment the case runs under (NAME=value, or \"\").\n";
    print "import { std::collections::DynamicArray };\nexport { uriInputs, uriOutputs, uriErrors, uriEnvironments };\n\n";
    my @cols = ([0, "uriInputs"], [1, "uriOutputs"], [2, "uriErrors"], [3, "uriEnvironments"]);
    for my $c (@cols) {
        my ($i, $name) = @$c;
        print "fn DynamicArray<string> $name() {\n    DynamicArray<string> v = DynamicArray.empty();\n";
        for my $t (@tests) {
            my @t = @$t;
            my $val;
            if ($i == 3) { my %env = @t[3 .. $#t]; $val = join(";", map { "$_=$env{$_}" } sort keys %env); }
            elsif ($i == 2) { ($val = $t[2]) =~ s/^libpq_uri_regress: //; }
            else { $val = $t[$i]; }
            print "    v.add(item: " . lit($val) . ");\n";
        }
        print "    return v;\n}\n\n";
    }
' "$tmp/001_uri.pl" "$COMMIT" > "$ROOT/tests/unit/src/uri_vectors.kama"

echo "gen-libpq-tables: $(grep -c 'k.add' "$ROOT/src/conninfo/keywords.kama") keywords, $(grep -c 'e.add' "$ROOT/src/conninfo/keywords.kama") environment options, $(grep -c 'v.add' "$ROOT/tests/unit/src/uri_vectors.kama" | awk '{print $1/4}') URI cases (PostgreSQL ${COMMIT%${COMMIT#????????}})"
