#!/bin/sh
# gen-session-vectors.sh — PostgreSQL's own tests of which server a connect settles on, as test vectors for the
# hermetic unit tests:
#
#   tests/unit/src/session_vectors.kama   every target_session_attrs case of src/test/recovery/t/001_stream_rep.pl
#                                         (test_target_session_attrs): the two nodes listed (the primary, or one of two
#                                         standbys), the mode, and the node the connect must reach, or "" where it
#                                         must fail; and src/interfaces/libpq/t/003_load_balance_host_list.pl's
#                                         load_balance_hosts scenario: the value it refuses and libpq's message,
#                                         how many connections it makes with random, how many each node must take,
#                                         and how many fall through to the one node left up
#
# The test is pinned to the same REL_18_STABLE commit as the other generators, by SHA256. Its cases are read from its
# calls, which name the nodes, the mode and the outcome; nothing is typed by hand. A call this generator cannot read
# is an error, so a new upstream case cannot be dropped silently.
#
# The generated file is committed. Regenerate, and check that `git diff` is empty (no server needed):
#
#   tools/gen-session-vectors.sh
set -eu

COMMIT=c45ba888d7af7b38e33832a0e240e34ca98ef866
STREAM_REP_SHA=5031c150c82928cfe9b6ce4e50a28d0e1170323956445087e8fbc87e6289b6ae
LOAD_BALANCE_SHA=172663cfd3d45f71aaacd5f187c58dcb0bd29625e4bf11a22e52ea7cbd824018

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

fetch() {  # fetch <path in the postgres tree> <local name> <sha256>
    if [ -n "${PG_SRC_DIR:-}" ] && [ -f "$PG_SRC_DIR/$1" ]; then cp "$PG_SRC_DIR/$1" "$tmp/$2"
    else curl -fsSL -o "$tmp/$2" "https://raw.githubusercontent.com/postgres/postgres/$COMMIT/$1"; fi
    got=$(shasum -a 256 "$tmp/$2" | cut -d' ' -f1)
    [ "$got" = "$3" ] || { echo "gen-session-vectors: $2 sha256 $got, want $3" >&2; exit 1; }
}

fetch src/test/recovery/t/001_stream_rep.pl 001_stream_rep.pl "$STREAM_REP_SHA"
fetch src/interfaces/libpq/t/003_load_balance_host_list.pl 003_load_balance_host_list.pl "$LOAD_BALANCE_SHA"

python3 - "$tmp" "$COMMIT" > "$ROOT/tests/unit/src/session_vectors.kama" <<'PY'
import re, sys

tmp, commit = sys.argv[1], sys.argv[2]
NODES = {"$node_primary": "primary", "$node_standby_1": "standby1", "$node_standby_2": "standby2", "undef": ""}

def fail(why):
    sys.stderr.write("gen-session-vectors: " + why + "\n")
    sys.exit(1)

text = open(tmp + "/001_stream_rep.pl", encoding="utf-8").read()
# The calls, not the sub's own definition: test_target_session_attrs(<node>, <node>, <node or undef>, "<mode>", <status>);
cases = []
for args in re.findall(r'^test_target_session_attrs\((.*?)\);', text, re.S | re.M):
    parts = [p.strip() for p in args.replace("\n", " ").split(",")]
    if len(parts) != 5:
        fail("a call with " + str(len(parts)) + " arguments: " + args)
    first, second, target, mode, status = parts
    if first not in NODES or second not in NODES or target not in NODES:
        fail("a node this generator does not know: " + args)
    m = re.fullmatch(r'"([a-z-]+)"', mode) or fail("a mode that is not a plain string: " + mode)
    if status not in ("0", "2"):
        fail("a status other than 0 or 2: " + status)
    want = NODES[target] if status == "0" else ""
    if (status == "0") != (target != "undef"):
        fail("a target and a status that disagree: " + args)
    cases.append((NODES[first], NODES[second], m.group(1), want))
if len(cases) < 17:
    fail("only " + str(len(cases)) + " cases found")

def column(name, values):
    out = ["fn DynamicArray<string> " + name + "() {", "    DynamicArray<string> v = DynamicArray.empty();"]
    out += ['    v.add(item: "' + x + '");' for x in values]
    out += ["    return v;", "}", ""]
    return out

out = ["// Generated by tools/gen-session-vectors.sh from PostgreSQL " + commit[:12] + " (REL_18_STABLE):",
       "// src/test/recovery/t/001_stream_rep.pl, test_target_session_attrs. Do not edit; regenerate.",
       "//",
       "// Case i: the nodes listed (tsaFirst, tsaSecond: primary, standby1 or standby2), target_session_attrs (tsaMode), and",
       "// the node the connect must reach (tsaReached), \"\" where it must fail.",
       "import { std::collections::DynamicArray };",
       "export { tsaFirst, tsaSecond, tsaMode, tsaReached, lbRefusedValue, lbRefusedMessage, lbRandomConnections, lbFloor,",
       "         lbFallThroughConnections };",
       ""]
out += column("tsaFirst", [c[0] for c in cases])
out += column("tsaSecond", [c[1] for c in cases])
out += column("tsaMode", [c[2] for c in cases])
out += column("tsaReached", [c[3] for c in cases])

# 003_load_balance_host_list.pl: the refused value and its message, the random loop's count and each node's floor
# (ok($nodeN_occurrences > 1, …)), and the fall-through loop's count.
lb = open(tmp + "/003_load_balance_host_list.pl", encoding="utf-8").read()
m = re.search(r'load_balance_hosts=(\w+)",\s*"[^"]*",\s*expected_stderr => qr/(.*?)/\)', lb, re.S) or fail("003: the refused value")
bad, message = m.group(1), m.group(2)
loops = [int(n) for n in re.findall(r'foreach my \$i \(1 \.\. (\d+)\)', lb)]
if len(loops) != 2:
    fail("003: expected two connection loops, found " + str(len(loops)))
floors = set(re.findall(r'ok\(\$node\d_occurrences > (\d+),', lb))
if len(floors) != 1:
    fail("003: expected one floor for every node, found " + str(floors))
out += ["// 003_load_balance_host_list.pl.",
        "fn string lbRefusedValue() { return \"" + bad + "\"; }",
        "fn string lbRefusedMessage() { return \"" + message.replace('"', '\\"') + "\"; }",
        "fn isize lbRandomConnections() { return " + str(loops[0]) + "; }",
        "fn isize lbFloor() { return " + floors.pop() + "; }",
        "fn isize lbFallThroughConnections() { return " + str(loops[1]) + "; }",
        ""]
print("\n".join(out).rstrip("\n"))
PY
echo "gen-session-vectors: wrote tests/unit/src/session_vectors.kama"
